services:
  budget_sandbox_db:
    image: postgres:15.3
    networks:  
      - nginx_network
    healthcheck:
      test: "exit 0"
    restart: always
    ports:
      - 4432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=budget_sandbox_db
    volumes:
      - budget-sandbox-data:/var/lib/postgresql/data    
  budget_sandbox_api:
    build:
      context: .
    networks:  
      - nginx_network
    ports: 
      - "5000:5000"
    depends_on:
      budget_sandbox_db:
        condition: service_healthy
    environment:
      - Keycloak__ClientSecret=simplesecret
      - PostgresDatabaseConnection=Host=budget_sandbox_db;Port=5432;Database=budget_sandbox_db;Username=postgres;Password=docker
volumes:
  budget-sandbox-data:
networks:
  nginx_network:
    external: true